[[keyboard.bindings]]
key = "F"
mods = "Control"

[keyboard.bindings.command]
args = ["$(fzf)"]
program = "nano"

[mouse]

[[mouse.bindings]]
action = "Paste"
mouse = "Right"

[general]
import = ["/home/dragon/.config/alacritty/dracula.toml"]

[font]
size = 14.0

[font.normal]
#family = "JetbriansMono nerd Font"

[window]
decorations = "buttonless"
opacity = 1.0
title = "terminal"

[window.padding]
x = 10
y = 4

[keyboard]
